### PR TITLE
[IMPROVE] Make the Action faster

### LINKED ISSUE #2: [FEATURE REQUEST] Make the Action Faster
First of all, excellent action for uploading search indexes to algolia!
I am using it it for a [documentation repo](https://github.com/uinstinct/important_cp).

Currently, the action is taking around *1.5 mins* to complete which is according to me okay but can be certainly improved.

on github actions

If we can speed up the build using caching, it would be awesome.
I found one example: https://pythonspeed.com/articles/speeding-up-docker-ci/

If this idea can work out, I am willing to collaborate.
Thank you.

### PR DESCRIPTION
**Pull request by aditya-mitra**
# Short Description

Instead of using the [docker image by algolia](https://docsearch.algolia.com/docs/run-your-own/#run-the-crawl-from-the-docker-image) for docsearch, this pr uses [the source repository](https://github.com/algolia/docsearch-scraper) for scrapping and uploading to algolia.

# Details

Using the source repository, removes the use of [jq](https://github.com/stedolan/jq/wiki/Installation), installation of docker-cli, the algolia docsearch docker image, and other peer dependencies.

Using the [python:3.6](https://hub.docker.com/_/python) as the base image (which comes with git preinstalled), first the [algolia-docsearch repository](https://github.com/algolia/docsearch-scraper) is _git cloned_.
`pipenv` is installed and then `pipenv` installed the packages in the Pipfile.

With these setup, now we can easily run:
```
python docsearch run $GITHUB_WORKSPACE/$FILE
```

# Improvements

The running time of the action has now **reduced by 40 seconds**.

You can have a look at the comparison run in [here](https://github.com/aditya-mitra/temptemp/actions/runs/963793337)

image

# Further Comments

I have made a few other fixes/corrections like correcting the spelling of algolia.

Also, I changed the `config.example.json` since it took a lot of time to index and the difference could not have been made clear.

# Related Issues

Closes #2

### CODE REVIEW

**Comment by aditya-mitra** [comment]
Please do squash and merge :smiley: 
I have made some irrelevant commits

**Review by darrenjennings — APPROVED** [review]
this is great, I think the speed of the action outweighs the cons. I originally used docker because using the algolia/docsearch-scraper image meant we did not have to worry about what was being used under the hood (maybe tomorrow they rewrite it in rust 😅). Thanks, I don't use this action anymore so if you could test it as needed and let me know of any issues!

**Comment by darrenjennings** [comment]
released latest version and published to marketplace https://github.com/marketplace/actions/algolia-docsearch-indexer

**Comment by aditya-mitra** [comment]
> this is great, I think the speed of the action outweighs the cons. I originally used docker because using the algolia/docsearch-scraper image meant we did not have to worry about what was being used under the hood (maybe tomorrow they rewrite it in rust ). Thanks, I don't use this action anymore so if you could test it as needed and let me know of any issues!

Thanks a lot!

I thought I could further improve the speed (at least another reduction by 25 seconds) if we used a custom docker image with the **docsearch repository** installed. And with the docker's caching systems, we would only be requiring the final layer.

But, I thought publishing a Docker image to docker hub would require further discussions and publishing the image to docker hub.

**Pull request merged**
